version: '3.7'
services:
  www:
    build: .
    ports:
      - '${WEB_PORT:-80}:80'
    volumes:
      - ./www/:/var/www/html/
      - ./php/php.ini:/usr/local/etc/php/php.ini
      - ./httpd/apache2.conf:/etc/apache2/apache2.conf
      - ./logs/apache_access.log:/var/log/apache2/access.log
      - ./logs/apache_error.log:/var/log/apache2/error.log
    links:
      - db
      - php

  php:
    build: .
    volumes:
      - ./www:/var/www/html
      - ./php/php.ini:/usr/local/etc/php/php.ini
    links:
      - db

  db:
    image: mysql:${MYSQL_VERSION:-latest}
    command:
      - "--default-authentication-plugin=mysql_native_password"
      - "--character-set-server=utf8"
      - "--collation-server=utf8_unicode_ci"
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-wt_dev}
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    volumes:
      - ./dump:/docker-entrypoint-initdb.d
      - persistent:/var/lib/mysql
      - ./logs/:/var/log/mysql/
      - ./mysql/mysql.cnf:/etc/mysql/conf.d/my.cnf
    ports:
      - '${MYSQL_PORT:-3306}:3306'
      - '${MYSQL_PORT_RESERV:-33060}:33060'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - db:db
    ports:
      - '${PHPMYADMIN_PORT:-80}:80'
    environment:
      MYSQL_USER: ${MYSQL_USER:-mysql}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-mysql}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-root}
    depends_on:
      - db

volumes:
  persistent:
